# Generated by Django 5.2.1 on 2025-07-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_delete_award'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='gpa',
        ),
    ]
